AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaFunctionOverHttps:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function.handler
      Runtime: python3.9
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/configuration'
            Method: get